#!/bin/bash

user_id=$( id -u )
group_id=$( id -g )

sudo mkdir -p /mnt/games && sudo mkdir -p /mnt/nas
sudo umount /dev/nvme1n1p2 || /bin/true
sudo mount /dev/nvme1n1p2 /mnt/games -a -o noatime,nodev,nosuid,uid=${user_id},gid=${group_id}
sudo umount /dev/sda2 || /bin/true
sudo mount /dev/sda2 /mnt/nas -a -o noatime,nodev,nosuid,uid=${user_id},gid=${group_id}
