#!/bin/bash

sudo pacman -S --needed --noconfirm base-devel git less unzip ntfs-3g gnome-themes-extra adobe-source-code-pro-fonts ttf-font-awesome ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -s --noconfirm
rm -rf ../paru
