#!/bin/bash

sudo pacman -Sy multilib
sudo pacman -S --noconfirm steam lib32-nvidia-utils gamemode lib32-gamemode

sudo gpasswd -a $USER gamemode
echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
