#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

sudo pacman -Sy --noconfirm multilib
sudo pacman -S --noconfirm steam lib32-nvidia-utils gamemode lib32-gamemode

# Steam
cp -r $script_dir/../env/.local $HOME/.local
echo "__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1" | sudo tee -a /etc/environment
echo "__GL_SHADER_DISK_CACHE_SIZE=100000000000" | sudo tee -a /etc/environment

# Gamemode
sudo gpasswd -a $USER gamemode
echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

# Networking
echo 'net.core.rmem_max=16777216' | sudo tee -a /etc/sysctl.conf
echo 'net.core.wmem_max=16777216' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
