#!/bin/bash

# Install Homebrew
if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # Add brew to PATH (Apple Silicon)
    eval "$(/opt/homebrew/bin/brew shellenv)"
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
fi
brew update
brew cleanup

xcode-select --install
brew install git less unzip font-roboto

cp -r $HOME/sun/env/.local/scripts $HOME/.local
