#!/bin/bash

set -e

JDK_VERSION=21
JAVA_HOME_EXPORT='export JAVA_HOME=$(/usr/libexec/java_home -v '"$JDK_VERSION"')'
JAVA_HOME_PATH_EXPORT='export PATH=$PATH:$JAVA_HOME/bin'

ANDROID_CMD_VERSION='13114758'
ANDROID_PLATFORM_VERSION='35'
ANDROID_BUILD_TOOLS_VERSION='35.0.1'
ANDROID_CMD_PATH='cmdline-tools'
ANDROID_SDK_PATH="$HOME/Library/Android/sdk"
ANDROID_SDK_EXPORT='export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk'
ANDROID_SDK_PATH_EXPORT='export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools'

NVM_VERSION='0.40.4'
NODE_VERSION=24

CODIUM_USER_PATH='Library/Application Support/VSCodium/User'

cp -r $HOME/sun/env/.local/scripts $HOME/.local

echo "Installing Visual Studio Codium..."
brew install --cask vscodium
mkdir -p "$HOME/${CODIUM_USER_PATH}"
cp "$HOME/sun/env/${CODIUM_USER_PATH}/settings.json" "$HOME/${CODIUM_USER_PATH}/settings.json"
cp "$HOME/sun/env/${CODIUM_USER_PATH}/keybindings.json" "$HOME/${CODIUM_USER_PATH}/keybindings.json"

echo "Installing JDK..."
brew install openjdk@${JDK_VERSION}
sudo ln -sfn "$(brew --prefix openjdk@${JDK_VERSION})/libexec/openjdk.jdk" "/Library/Java/JavaVirtualMachines/openjdk-${JDK_VERSION}.jdk"
if ! grep -q "$JAVA_HOME_EXPORT" $HOME/.zprofile 2>/dev/null; then
  echo "$JAVA_HOME_EXPORT" >> $HOME/.zprofile
  echo "$JAVA_HOME_PATH_EXPORT" >> $HOME/.zprofile
  source $HOME/.zprofile
fi

echo "Installing Android SDK..."
rm -rf ${ANDROID_SDK_PATH}/${ANDROID_CMD_PATH}
mkdir -p ${ANDROID_SDK_PATH}/${ANDROID_CMD_PATH}
curl -L -o $HOME/commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-${ANDROID_CMD_VERSION}_latest.zip
unzip $HOME/commandlinetools.zip -d ${ANDROID_SDK_PATH}/${ANDROID_CMD_PATH}
rm -f $HOME/commandlinetools.zip
mv ${ANDROID_SDK_PATH}/${ANDROID_CMD_PATH}/cmdline-tools ${ANDROID_SDK_PATH}/${ANDROID_CMD_PATH}/latest
if ! grep -q "$ANDROID_SDK_EXPORT" $HOME/.zprofile 2>/dev/null; then
  echo "$ANDROID_SDK_EXPORT" >> $HOME/.zprofile
  echo "$ANDROID_SDK_PATH_EXPORT" >> $HOME/.zprofile
  source $HOME/.zprofile
fi
sdkmanager "platform-tools" "platforms;android-$ANDROID_PLATFORM_VERSION" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

echo "Installing Go..."
brew install go

echo "Installing NodeJS..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
source $HOME/.zprofile
nvm install $NODE_VERSION